Ot132 16 Crear modelo y repositorio base de Roles
alkemyTech/OT132-SERVER pull request #1
Opened 2022-01-19 22:59 UTC by KharonBlue

2022-01-19 23:22 UTC, KharonBlue commented
21500be8696aecf60c9c0693705ee2a1bc953402
Commit "Change in entity Role"

2022-01-20 09:37 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/entity/Role.java
> +  private Calendar ROLE_TIMESTAMP;
Como se menciona el ticket, este atributo debe ser una instancia de Timestamp y se debe llamar timestamp, en el caso de la base de datos se debe llamar "TIMESTAMP" para cumplir con los estándares del README.md

Para especificar que es el tiempo de creación se puede incorporar la annotation @CreationTimestamp como se mencionó en la planning.

2022-01-20 09:41 UTC, mkain0 requested changes

2022-01-20 09:41 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/entity/Role.java
> +  private Calendar ROLE_TIMESTAMP;
Por favor, revisar el PR de OT132-28 para resolver los problemas presentes en esta clase, ya que la misma no cumple con el estándar del código de este proyecto.

2022-01-20 17:26 UTC, mkain0 requested changes

2022-01-20 17:26 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/entity/Role.java
> +  @Column(name = "ID_ROLE", nullable = false)
ROLE_ID debería ser la forma correcta para nombrar a este campo después de mergearse el PR de @AgosBC

2022-01-20 17:26 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/entity/Role.java
> +  private Long id;
Al mergearse el PR de @AgosBC la forma correcta de nombrar a este atributo seria roleId

2022-01-20 17:26 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/entity/Role.java
> +  @Column(name = "ROLE_TIMESTAMP")
Esta columna se debe llamar TIMESTAMP

2022-01-20 18:49 UTC, mkain0 approved these changes

2022-01-20 18:49 UTC, merged