OT132-74: model, repository and service creation for Comments
alkemyTech/OT132-SERVER pull request #17
Opened 2022-01-22 19:42 UTC by nardo1285

This class needs the imports from classes "Users" and "News".

2022-01-22 21:12 UTC, mkain0 requested changes

2022-01-22 21:12 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/entity/Comment.java
> +  @Column(name = "COMMENTS_ID")
El nombre de esta columna debería ser COMMENT_ID para ser consistente con las otras entidades en este proyecto.

2022-01-22 21:12 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/entity/Comment.java
> +  private Long commentsId;
El nombre de este atributo debería ser commentId para ser consistente con las otras entidades en este proyecto.

2022-01-22 21:12 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/entity/Comment.java
> +  @ManyToOne
Falta definir el fetch type y el cascade mode.

2022-01-22 21:12 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/entity/Comment.java
> +  @ManyToOne
Falta definir el fetch type y el cascade mode.

Si tenes dudas como funcionan, podes consultar a @AlejoGalizzi :)

2022-01-22 21:12 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/entity/Comment.java
> +
Esto no esta en el scope del ticket, así  que acá estoy actuando por análisis... si alguien postea un comentario, lo más seguro es que cuando lo guarde en la BD quiera guardar la fecha en que se creo el comentario para luego cuando tenga que listar todos los comentarios relacionados a un post o novedad, pueda devolverlos ordenamos por fecha. De esa forma el comentario agrega un valor al negocio. 

Aprovechando que todavía tenemos tiempo en el Spring, agreguemos una columna TIMESTAMP como la que hemos agregado en otras entidades con la annotation @CreationTimestamp para poder agregarle valor a esta entidad.

2022-01-23 16:54 UTC, nardo1285 commented on src/main/java/com/alkemy/ong/model/entity/Comment.java
> +  @ManyToOne
El fetch aquí no me pareció necesario declararlo ya que para ManyToOne, su valor por default es EAGER. Y como cada comentario tiene 1 usuario, entendí que no era necesario cambiarlo para optimizar el uso de recursos. 
El cascade mode tampoco me pareció necesario en sus opciones, ya que no deseo que este atributo genere alguna propagación a la entidad User. Por ejemplo, si elimino el comentario, no quiero que la eliminación se propague al usuario. 

De todas formas, @AlejoGalizzi la tiene mucho mas clara, asique me gustaría charlarlo con él a ver que opina y ver si el criterio que usé está bien aplicado (también recibo comentarios tuyos, obvio).

Nota: esto aplica también al otro comment de ManyToOne.

2022-01-23 16:55 UTC, nardo1285 commented on src/main/java/com/alkemy/ong/model/entity/Comment.java
> +
Me parece perfecto! Será agregado :)

2022-01-24 19:28 UTC, mkain0 approved these changes

2022-01-24 19:29 UTC, merged