OT132-28  Crear modelo y repositorio de Slides
alkemyTech/OT132-SERVER pull request #2
Opened 2022-01-19 23:00 UTC by KharonBlue

2022-01-19 23:24 UTC, KharonBlue commented
1106ea2bce1d19231b22f0b000dbb13d3b0310c7
Commit "Entity Slide with his repository added"

2022-01-20 09:33 UTC, mkain0 requested changes

2022-01-20 09:33 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/entity/Role.java
> +}
Esta entidad no es parte del scope del ticket.

2022-01-20 09:33 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/entity/Slide.java
> +@Table(name = "Slides")
Como se menciona en el README.md, todo lo referido a SQL debe estar utilizando MAYUSCULAS y GUIONES BAJOS en los casos que el nombre este compuesto por mas de una palabra.

Esto debería ser SLIDES.

2022-01-20 09:33 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/entity/Slide.java
> +  @Column(name = "ID_SLIDE")
Esta columna debería ser nullable=false.

2022-01-20 09:33 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/entity/Slide.java
> +  private Long ID_SLIDE;
Todos los nombres de atributos en java debe escribirse en minúscula a menos que sea una constante. Por favor, modificar todos los nombres de los atributos de las entidades para que sigan el formato definido en el README.md

2022-01-20 09:33 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/entity/Slide.java
> +  private Integer SLIDE_ORDER;
Esta bien que la columna en la base de datos se llame SLIDE_ORDER porque ORDER es una palabra reservada, pero el atributo en JAVA se debe llamar como de acuerdo a los criterios de aceptación del ticket, es decir, que este atributo debería ser order.

2022-01-20 09:33 UTC, mkain0 commented on src/main/java/com/alkemy/ong/repository/RoleRepository.java
> +}
Esta clase no es parte del scope de este ticket.

2022-01-20 17:29 UTC, mkain0 approved these changes

2022-01-20 17:29 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/entity/Slide.java
> +  private Long id;
MINOR: me encargo de este cambio ya que es uno solo y aparece después de mergear el PR de @AgosBC

2022-01-20 17:29 UTC, merged