OT132-39: Reusable image upload service
alkemyTech/OT132-SERVER pull request #26
Opened 2022-01-28 18:00 UTC by AlejoGalizzi

I create a controller that i erase later, but here is the response when i upload an image that i put in the params.
![image](https://user-images.githubusercontent.com/81248632/151597928-bf84e72d-00cc-4e17-80dc-6e7bb2c3030c.png)

2022-01-28 23:11 UTC, mkain0 requested changes

2022-01-28 23:11 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/UploadImageService.java
> +package com.alkemy.ong.service;
Esta clase es un util, por lo tanto, debería estar en el package common.

2022-01-28 23:11 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/abstraction/IUploadImageUrl.java
> +public interface IUploadImageUrl {
Esta interfaz no agrega valor porque el uploadImage es un util, no debería haber diferentes implementaciones de este útil.

2022-01-28 23:11 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/abstraction/IUploadImageUrl.java
> +  String uploadImage(InputStream input, ObjectMetadata contentType, String fileName);
Si deberíamos crear una interfaz para obtener el inputStream, el contentType y el fileName.

```
public interface IUploadContent {
 String getContentName();
 String getContentType();
 InputStream getInputStream();
}
```

No utilizaría el nombre Image porque S3 permite subir cualquier tipo de archivo.

2022-01-28 23:11 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/UploadImageService.java
> +  public String uploadImage(InputStream input, ObjectMetadata contentType, String fileName) {
`public String update(IUploadContent content)`

2022-01-28 23:11 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/UploadImageService.java
> +      PutObjectRequest request = new PutObjectRequest(bucketName, fileName, input, contentType);
El ObjectMetadata debe ser instanciado dentro del contexto de este método para dejar al librería wrapeada en este util. Esto permite reemplazarla en un futuro por cualquier otra librería sin tener un algo impacto en el proyecto.

```
    ObjectMetadata metadata = new ObjectMetadata();
    metadata.setContentType(contentType);
```

2022-01-28 23:11 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/UploadImageService.java
> +      return String.valueOf(amazonS3.getUrl(bucketName, fileName));
En vez de utilizar String#valueOf, conviene utilizar los métodos propios de la JDK para URL. La clase URL tiene su propio toString:

`amazonS3.getUrl(bucketName, fileName).toString();`

2022-01-29 00:16 UTC, AlejoGalizzi commented on src/main/java/com/alkemy/ong/exception/UploadErrorException.java
> +public class UploadErrorException extends RuntimeException {
Te referis que en ves de utilizar este UploadServiceException use el External??

2022-01-29 00:24 UTC, AlejoGalizzi commented on src/main/java/com/alkemy/ong/exception/ErrorObject.java
> +  private String message;
Cual seria la mejor manera de setear los mensajes en el handler?? Porque el external cuando quiero obtener los mensajes me retorna solo uno.
![imagen_2022-01-28_212410](https://user-images.githubusercontent.com/81248632/151638707-d1ef0b19-9506-4ed7-abe9-2646a132fffb.png)

2022-01-30 01:31 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/UploadImageService.java
> +  public String uploadImage(InputStream input, ObjectMetadata contentType, String fileName) {
@AlejoGalizzi Esta fue una metida de pata mia cuando hice el CR xD upload quise poner y puse otra fruta.

2022-01-30 01:37 UTC, mkain0 commented on src/main/java/com/alkemy/ong/exception/ErrorObject.java
> +  private String message;
El getMessage para este caso es suficiente. Dependiendo de la exception se pueden hacer cosas diferentes. Todo depende de los métodos que tenga la exception. Como mencioné anteriormente como ejemplo, MethodArgumentNotValidException tiene un FieldError, cada uno tiene un mensaje de error que debería ser guardado en la Lista de Strings de ErrorResponse.

2022-01-30 01:41 UTC, mkain0 approved these changes

2022-01-30 01:44 UTC, merged