Ot132 40
alkemyTech/OT132-SERVER pull request #27
Opened 2022-01-29 23:57 UTC by intisolar

2022-01-30 02:55 UTC, mkain0 requested changes

2022-01-30 02:55 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +  @GetMapping("/list")
Esta no es la URL que corresponde a un list en REST.

2022-01-30 02:55 UTC, mkain0 commented on src/test/java/com/alkemy/ong/controller/CategoryControllerTest.java
> +public class CategoryControllerTest {}
Por favor remover esta clase ya que no cumple ninguna función.

2022-01-30 02:55 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/abstraction/IGetCategoryDetails.java
> +  List<CategoryResponse> findAllCategories();
findAll o list es suficiente para definir lo que hace el método. El tipo de retorno ya te brinda la información de que se esta trayendo, además del nombre de la interfaz.

2022-01-30 02:55 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/CategoryService.java
> +  @Autowired private CategoryMapper mapper;
categoryMapper > esto se a explicado en otros PRs.

2022-01-30 02:55 UTC, mkain0 commented on src/main/java/com/alkemy/ong/repository/ICategoryRepository.java
> +  public List<Category> findAllActiveCategories();
JPA permite hacer esto directamente utilizando: findBySoftDeleteFalse. No es necesario utilizar JPQL para esta query.

2022-01-30 02:55 UTC, mkain0 commented on src/main/java/com/alkemy/ong/config/segurity/SecurityConfig.java
> +  @Autowired private UserDetailsService userDetailsService;
REVERT: Estos cambios no deberían estar en el PR. Hacen ruido y no estan siguiendo el formato que tenemos en otras clases.

2022-01-30 02:55 UTC, mkain0 commented on src/main/java/com/alkemy/ong/config/segurity/SecurityConfig.java
> +  @Autowired private JwtRequestFilter jwtRequestFilter;
REVERT: Estos cambios no deberían estar en el PR. Hacen ruido y no estan siguiendo el formato que tenemos en otras clases.

2022-01-30 02:55 UTC, mkain0 commented on src/main/java/com/alkemy/ong/config/segurity/SecurityConfig.java
> +    managerBuilder.userDetailsService(userDetailsService).passwordEncoder(passwordEncoder());
REVERT: Estos cambios no deberían estar en el PR. Hacen ruido y no estan siguiendo el formato que tenemos en otras clases.

2022-01-30 02:55 UTC, mkain0 commented on src/main/java/com/alkemy/ong/config/segurity/SecurityConfig.java
> +        .antMatchers(HttpMethod.GET, "/categories/list")
Esta URL no es la correcta para una implementación de REST.

2022-01-30 02:55 UTC, mkain0 commented on src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
> +  public List<CategoryResponse> listMap(List<Category> categories) {
Este método debería llamarse map para ser consistente con los métodos de los otros mappers.

2022-01-30 02:55 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/CategoryService.java
> +  @Autowired private ICategoryRepository categoryRepository;
Por favor, seguir el formato utilizado en otras clases para la declaración de las clases inyectadas.

2022-01-30 02:55 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    return ResponseEntity.ok().body(categoryList);
Este servicio no tiene el response esperado. Por favor, revisar los servicios existentes como guía.
Podes consultar a @FrancoGL que esta free si necesitas ayuda.

2022-01-30 02:55 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +  @Autowired private IGetCategoryDetails getCategoryDetails;
Por favor, seguir el formato utilizado en otras clases para la declaración de las clases inyectadas.

2022-01-30 02:55 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +  public ResponseEntity<List<CategoryResponse>> getListOfCategories() {
Este método se debería llamar list o findAll. Como mencioné en otros PRs, el tipo de retorno o los parámetros me brindan el resto de la información.

2022-01-30 02:55 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    List<CategoryResponse> categoryList = getCategoryDetails.findAllCategories();
categoryList > Como he mencionado en otros PRs, no es buena práctica utilizar el nombre de las implementaciones o el tipo de dato en los nombres de las variables.

2022-01-30 02:55 UTC, mkain0 commented on src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
> +    List<CategoryResponse> categoryResponseList = new ArrayList<>();
categoryResponseList > Como he mencionado en otros PRs, no es buena práctica utilizar el nombre de las implementaciones o el tipo de dato en los nombres de las variables.

Por otro lado, para performance: new ArrayList<>(categories.size()). Para más info consultar a otros compañeros ya que este comentario se ha puesto en más de 3 PRs.

2022-01-30 02:55 UTC, mkain0 commented on src/main/java/com/alkemy/ong/mapper/CategoryMapper.java
> +    for (Category aux : categories) {
aux no es un nombre representativo. Un nombre apropiado seria category.

2022-01-30 19:08 UTC, intisolar commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +  @Autowired private IGetCategoryDetails getCategoryDetails;
te referís al autowired en la misma línea? Me lo hace automáticamente el formatter de Google, pero lo puedo setear manualmente, si es eso.

2022-01-30 20:16 UTC, intisolar commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    List<CategoryResponse> categoryList = getCategoryDetails.findAllCategories();
y qué se suele poner? Por que no es que tiene que ser descriptivo a su vez? Cuando te referís al tipo de dato es a List y no al objeto Category? Si le pongo categories también estaría mal?

2022-01-30 23:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +  @Autowired private IGetCategoryDetails getCategoryDetails;
Arreglalo manualmente. Aunque me extraña que te lo haga automáticamente 🤔

2022-01-30 23:58 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +    List<CategoryResponse> categoryList = getCategoryDetails.findAllCategories();
Consúltalo con tus compañeros, ya que esto lo hemos conversado en varios PRs.

2022-01-31 17:46 UTC, intisolar commented
![image](https://user-images.githubusercontent.com/93158217/151845490-880e16e7-1dd1-493f-ba84-3662d34dea76.png)

2022-01-31 21:10 UTC, mkain0 requested changes

2022-01-31 21:10 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +  public ResponseEntity<List<CategoryResponse>> list() {
La response de este servicio no cumple con el JSON expected.

2022-01-31 21:11 UTC, mkain0 approved these changes

2022-01-31 21:13 UTC, merged