OT132-69: enpoint to create members
alkemyTech/OT132-SERVER pull request #34
Opened 2022-01-31 21:45 UTC by FrancoGL

Modified:
<ul>
<li>SecurityConfig</li>
<li>MemberController</li>
<li>MemberMapper</li>
<li>MemberService</li>
</ul>
Created:
<ul>
<li>CreateMemberRequest</li>
<li>ICreateMember</li>
</ul>
<h2>Postman</h2>
<h3>Success</h3>

![Imgur](https://i.imgur.com/6xtQSZ9.png)

<h3>Name error</h3>

![Imgur](https://i.imgur.com/DYCCkEq.png)

<h3>Image error</h3>

![Imgur](https://i.imgur.com/1mU2M7l.png)

<h3>Name + Image</h3>

![Imgur](https://i.imgur.com/2wamriA.png)

2022-01-31 21:48 UTC, FrancoGL commented on src/main/java/com/alkemy/ong/model/request/CreateMemberRequest.java
> +  private String image;
Image fue definida como not null, por tanto, necesita la validación.

2022-01-31 22:54 UTC, mkain0 requested changes

2022-01-31 22:54 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/request/CreateMemberRequest.java
> +  @Pattern(regexp = "^[A-Za-z]*$", message = "The name has to contain only letters")
:D Nice!

2022-01-31 22:54 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/MemberService.java
> +    return memberMapper.map(member);
`return memberMapper.map(memberRepository.save(member));`

2022-01-31 22:54 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/MemberService.java
> +    memberRepository.save(member);
Dentro del repositorio se debería setear el softDelete como false.

2022-01-31 22:54 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/request/CreateMemberRequest.java
> +  @NotBlank(message = "Image is mandatory")
MINOR: para ser consistente con los mensajes que existen en el proyecto lo modificaría a: "Image cannot be null or empty."

2022-01-31 22:54 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/request/CreateMemberRequest.java
> +  @NotBlank(message = "Name is mandatory")
MINOR: para ser consistente con los mensajes que existen en el proyecto lo modificaría a: "Name cannot be null or empty."

2022-02-01 12:19 UTC, mkain0 approved these changes

2022-02-01 12:19 UTC, merged