Ot132 46
alkemyTech/OT132-SERVER pull request #36
Opened 2022-02-01 21:54 UTC by intisolar

![image](https://user-images.githubusercontent.com/93158217/152057764-e0fab0b1-9fcc-43b4-8c1d-662ce8d04f5d.png)
todavía no logré arreglar el tema de formato. 7
![1](https://user-images.githubusercontent.com/93158217/152057845-263a6438-aadf-4341-bf3f-404a9d806fb6.png)

2022-02-02 11:38 UTC, mkain0 commented
@intisolar Por favor, revisa el PR con tus compañeros y realiza los updates necesarios para cumplir con el scope del ticket y estándar del proyecto. Un buen punto de partida son aquellos que ya trabajaron en create operations: @facubc @FrancoGL @KharonBlue y/o @AgosBC.  

@facubc @FrancoGL @KharonBlue y/o @AgosBC: si quieren pueden aprovechar y dejar los comentarios sobre el PR. 

Una vez que este completa la review de al menos uno de ellos, por favor, notificarme para realizar la review de mi parte.

Gracias!

2022-02-02 13:56 UTC, FrancoGL commented on src/main/java/com/alkemy/ong/controller/NewsController.java
> +  public ResponseEntity<NewsResponse> postNews(@RequestBody @Valid NewsRequest newsRequest) {
Para ser consistente con el resto del proyecto, modificaría el nombre del método a create.

2022-02-02 14:00 UTC, FrancoGL commented on src/main/java/com/alkemy/ong/mapper/NewsMapper.java
> +    news.setTimestamp(new Timestamp(System.currentTimeMillis()));
No es necesario setear el timestamp, ya que este se genera de manera automática al guardar la entidad en la DB.

2022-02-02 14:02 UTC, FrancoGL commented on src/main/java/com/alkemy/ong/mapper/NewsMapper.java
> +  public NewsResponse responseMapper(News news) {
Para ser consistente con el resto del proyecto, modificaría el nombre del método a map.

2022-02-02 14:04 UTC, FrancoGL commented on src/main/java/com/alkemy/ong/model/request/NewsRequest.java
> +  @NotBlank(message = "The field name cannot be blank.")
Para ser consistente con los mensajes que existen en el proyecto lo modificaría a: "Name cannot be null or empty."

2022-02-02 14:05 UTC, FrancoGL commented on src/main/java/com/alkemy/ong/model/request/NewsRequest.java
> +  @NotBlank(message = "The field text cannot be blank.")
para ser consistente con los mensajes que existen en el proyecto lo modificaría a: "Text cannot be null or empty."

2022-02-02 14:05 UTC, FrancoGL commented on src/main/java/com/alkemy/ong/model/request/NewsRequest.java
> +  @NotBlank(message = "The field image cannot be blank.")
Para ser consistente con los mensajes que existen en el proyecto lo modificaría a: "Image cannot be null or empty."

2022-02-02 20:25 UTC, mkain0 requested changes

2022-02-02 20:25 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/request/NewsRequest.java
> +public class NewsRequest {
CreateNewsRequest para ser consistente con lo definido en las otras operaciones create.

2022-02-02 20:25 UTC, mkain0 commented on src/main/java/com/alkemy/ong/mapper/NewsMapper.java
> +    newsResponse.setTimestamp(news.getTimestamp());
TRIVIAL: el timestamp podría no estar en la request para ser consistente con algunos de los otros servicios que tenemos.

2022-02-02 20:25 UTC, mkain0 commented on src/main/java/com/alkemy/ong/repository/ICategoryRepository.java
> +  Category findByNameIgnoreCase(String name);
Nice! al utilizar el ignoreCase.

2022-02-02 20:25 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/NewsController.java
> +    return ResponseEntity.ok(newsResponse);
Segun REST, las operaciones de create devuelve un 201, no un 200.

2022-02-02 20:25 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/NewsService.java
> +  }
Este método no es necesario, pues la variable newsResponse no es necesaria en el contexto de este método y lo único que se encapsula es `return newsMapper.map(news);`

2022-02-02 20:25 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/NewsService.java
> +  @Autowired private ICategoryRepository categoryRepository;
Por favor, aplicar el formatter correspondiente para que queden: 

```
@Autowired 
private INewsRepository newsRepository;

@Autowired 
private NewsMapper newsMapper;

@Autowired 
private ICategoryRepository categoryRepository;
```

2022-02-02 20:25 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/NewsService.java
> +
News tiene un softDelete que se debería setear en false en el contexto de este ticket.

2022-02-02 20:25 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/abstraction/IAddCategory.java
> +  Category add();
Esta interfaz hace que este método sea accesible por cualquier clase y hay dos cuestiones:

1. El nombre del método no es representativo de lo que hace. Si miramos la implementación, esta realizando una búsqueda por name, por lo tanto, el método se debería llamar find o get y debería tener un parámetro que sea categoryName, ya que devuelve una Category.
2. El método es implementado en el servicio de News. Eso no sería del todo acertado, ya que por la arquitectura del proyecto le correspondería estar dentro del CategoryService.

Por otro lado, no requiero pasar por el servicio para agregar la categoría a la news, directamente puedo inyectar el repositorio en el NewsService.

2022-02-02 20:25 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/NewsService.java
> +  }
Ver comentario en la declaración de la interfaz.

2022-02-03 04:07 UTC, intisolar commented on src/main/java/com/alkemy/ong/mapper/NewsMapper.java
> +    newsResponse.setTimestamp(news.getTimestamp());
Ok, me imaginé que al ser una noticia la hora y la fecha serían importantes más que en las otras clases..

2022-02-03 04:15 UTC, intisolar commented on src/main/java/com/alkemy/ong/service/NewsService.java
> +  }
Ah sobre el nombre del método, le pregunté a los chicos y no supieron contestarme.. ¿Por qué es buildResponse o buildListResponse y no solo build() en este caso?

2022-02-03 04:19 UTC, intisolar commented on src/main/java/com/alkemy/ong/service/NewsService.java
> +
esto es por algo en particular? El valor por defecto del boolean no es false? En la entidad está el valor primitivo, debería cambiarlo a Boolean?

2022-02-03 09:33 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/NewsService.java
> +
Si, el valor de un boolean no primitivo por default es false, pero si mañana cambio la entity... nadie va a recordar que acá (en esta funcionalidad) el valor del softDelete tendría que ser false porque no hay ningún unit test escrito al respecto. Por lo tanto, es imposible recordar o saber que la aplicación no va estar funcionando como se esperar. En este caso, se debe explícitamente setear en false.

2022-02-03 09:36 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/NewsService.java
> +  }
Mi comentario acá no tiene que ver con el nombre del método, tiene que ver con que estas creando un método para una sola línea de código. No tiene sentido wrapear una sola linea de código en un método al menos que sea un conjunto de operaciones binarias que se pasan a un if (CLEAN CODE).

2022-02-03 18:09 UTC, intisolar commented on src/main/java/com/alkemy/ong/service/NewsService.java
> +  }
sí, ya lo solucioné, perdón la falta de claridad. Además lo que me comentaste, tengo esa duda sobre el nombre del método.

2022-02-03 20:17 UTC, mkain0 commented
@intisolar Recorda hacer sync con main antes de solicitar request nuevamente porque hay conflictos :) 
Gracias!

2022-02-04 09:24 UTC, mkain0 requested changes

2022-02-04 09:24 UTC, mkain0 commented on src/main/java/com/alkemy/ong/mapper/NewsMapper.java
> +    news.setSoftDelete(false);
Eso se converso en otro PR. El seteo del softDelete con valor false no es responsabilidad del mapper. El mapper pasa los datos de una clase a otra. El valor false del softDelete solamente le corresponde a la operación de create.

2022-02-04 12:18 UTC, mkain0 approved these changes

2022-02-04 12:21 UTC, merged

2022-02-04 15:25 UTC, intisolar commented
> @intisolar Recorda hacer sync con main antes de solicitar request nuevamente porque hay conflictos :) Gracias!

Sí estuve lidiando con eso porque no sabía por qué no me traía los cambios, supuestamente estaba al día y no me di cuenta que había cambios en esta rama así que estuve bastante tiempo con eso, finalmente tuve que hacer pull de esta rama y no del main para poder hacer el push de mis cambios.