OT132-57: Creation's endpoint for Slides
alkemyTech/OT132-SERVER pull request #39
Opened 2022-02-02 15:02 UTC by AlejoGalizzi

Once we put the body that contains the String of the encode image and optionally the order and the headers of the file's name and the content type, it returns a SlideResponse as the following picture
![OT132-57 _ 1](https://user-images.githubusercontent.com/81248632/152178679-22fe432f-48a2-473e-b64f-5239412ec131.png)

Then we can check that the slide was succesfully saved in the database.
![OT132-57 _ 2](https://user-images.githubusercontent.com/81248632/152178830-a0af55e6-9934-4824-a28a-d42fd61dd7a3.png)

PS: In this example i don't insert any order in the body, so the program calculate the order of this slide.

2022-02-02 16:18 UTC, mkain0 requested changes

2022-02-02 16:18 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/request/CreateSlideRequest.java
> +  @NotBlank
Falta definir el mensaje de error en caso de que este atributo no sea enviado en la request.

2022-02-02 16:18 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/SlideService.java
> +      throw new ExternalServiceException(e.getMessage());
Cachear y lanzar la misma exception solamente incrementa el stracktrace. 
Simplemente dejar que la exception siga de largo.

2022-02-02 16:18 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/SlideService.java
> +  private ImageUtils utils;
MINOR: imageUtils en vez de utils. 
Hemos hecho similar comentario respecto a esto con mappers y repositories en PRs de Sprint anteriores.

2022-02-02 16:18 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/SlideService.java
> +      slide.setOrder(getOrder(request.getOrder()));
CODE CLEAN: podemos extraer este código a un método buildSlide que devuelva un Slide que después se enviara al slideRepository#save.

2022-02-02 16:18 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/SlideService.java
> +      order = slides.get(slides.size() - 1).getOrder() + 1;
PERFORMANCE: si tengo 5000 slides, te traes las 5000 slides con toda su información... query realmente costosa para solamente calcular el size. Por favor, modificar esta query para que utilice un max y me devuelva el max order de la tabla de Slide.

2022-02-02 16:18 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/SlideService.java
> +  private Integer getOrder(Integer order) {
En mi opinión, este método puede parecer raro si uno no mira la implementación del mismo, ya que se llama getOrder y le estoy pasando un order. Sin mirar los detalles de la implementación podría pensar que me devuelve el mismo order que le paso. 

Creo que renombrarlo de la siguiente forma haría que no requiera revisar o leer los detalles de la implementación para utilizarlo:

`private Integer calculateOrderOrDefault(Integer defaultOrder)`
o 
`private Integer getOrderOrDefault(Integer defaultOrder)`

2022-02-02 16:18 UTC, mkain0 commented on src/main/java/com/alkemy/ong/common/amazon/Image.java
> +    this.inputStream = new ByteArrayInputStream(file.getBytes());
Ese String es un encode value, si no se desencodea se esta guardando un String plano y no la imagen real.

Si le paso el contenido de este archivo [encoded-20220202161418.txt](https://github.com/alkemyTech/OT132-SERVER/files/7988192/encoded-20220202161418.txt) en la request de esta API con contentType: image/jpeg, cuando haga click en la URL que me devuelve el servicio debería ver: 
![small-icon-images-2](https://user-images.githubusercontent.com/10514601/152192870-b0f0aae9-fc24-46db-8ae3-928feb73cdc2.jpeg). 

Sin desencodearlo en el backend, no creo que sea eso lo que se este subiendo.

2022-02-02 17:14 UTC, AlejoGalizzi commented on src/main/java/com/alkemy/ong/service/SlideService.java
> +      order = slides.get(slides.size() - 1).getOrder() + 1;
Hay alguna manera utilzando el jpa, o me conviene realizar una query en el repositorio??

2022-02-03 09:30 UTC, mkain0 commented on src/main/java/com/alkemy/ong/repository/ISlideRepository.java
> +  @Query(value = "select MAX(slide_order) from Slides", nativeQuery = true)
Como mencioné en varias dailies, utilizar query nativa es mala práctica. Es el equivalente a no hacer uso del ORM. Por favor, modificar el código para que utilice JPQL.

2022-02-03 09:30 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/SlideService.java
> +      order = slides.get(slides.size() - 1).getOrder() + 1;
Creo que lo mas cómodo es utilizando JPQL. Las funciones que aplican al SQL nativo, también se pueden utilizar en JPQL/HQL. Podes utilizar max y coalesce.

2022-02-03 14:07 UTC, mkain0 approved these changes

2022-02-03 14:07 UTC, merged