Ot132 64
alkemyTech/OT132-SERVER pull request #50
Opened 2022-02-06 04:17 UTC by VladimirMorote

2022-02-06 04:17 UTC, VladimirMorote commented
#50

2022-02-07 09:39 UTC, mkain0 requested changes
@intisolar @AgosBC @facubc @FrancoGL @AlejoGalizzi @KharonBlue Por favor, revisen el scope de este ticket como equipo. Gracias!

2022-02-07 10:03 UTC, mkain0 commented
@VladimirMorote Para el próximo PR, recorda incluir al menos el título del ticket en el título del PR. El número de ticket no aporta mucha información cuando uno ve la lista de PR abiertos e intenta priorizar por funcionalidad.

Además, asegurate que no haya merge conflicts cuando abrís el PR. Caso contrario, no es posible revisar el PR ya que cuando arregles los conflictos el código cambiará y se requiere volver a revisar generando un doble esfuerzo.

Por otro parte, es fundamental utilizar mensajes representativos para los commits ya que un mensajes como "algo" no indica nada para las otras personas que lo ven. Siempre trabajamos con otras personas y hay que tener en cuenta que todos debemos poder entender de que estamos hablando/trabajando.

![Screenshot 2022-02-07 at 10 39 46](https://user-images.githubusercontent.com/10514601/152766764-92f7fc0c-4842-4396-b444-f142a67fb6a9.png)

Gracias!

2022-02-07 18:41 UTC, mkain0 commented
Gracias @FrancoGL por tu colaboración!

2022-02-07 18:42 UTC, merged