OT132-45: endpoint for News details
alkemyTech/OT132-SERVER pull request #61
Opened 2022-02-09 21:00 UTC by nardo1285

Tiempo record para éste ser, con verificación en Postman para el 404. :)

2022-02-09 22:29 UTC, mkain0 requested changes

2022-02-09 22:29 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/NewsController.java
> +  private IGetNewsDetails newsDetails;
El nombre de la variable debería ser getNewsDetails para ser consistente con el proyecto.

2022-02-09 22:29 UTC, mkain0 commented on src/main/java/com/alkemy/ong/mapper/NewsMapper.java
> +
Trata de evitar estos saltos que generar ruido en el PR, se agrega un archivo a revision que solo esta haciendo ruido en la revisión y que no tiene ningún cambio valido para el scope del ticket.

Incluso estas cosas pueden generar conflictos a otros compañeros si se mergea. Algo que se puede evitar simplemente no commiteando modificaciones innecesarias.

2022-02-09 22:29 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/NewsService.java
> +    return newsMapper.map(result.get());
La news pertenece a una categoría. Al menos un atributo categoryName debería ser agregado en el dto para mapear dicha información. También se puede agregar un objeto category, pero dado que no esta especificado en el ticket, ambas son perfectamente validas y la primera opción es la más simple.

2022-02-10 11:23 UTC, nardo1285 commented on src/main/java/com/alkemy/ong/service/NewsService.java
> +    return newsMapper.map(result.get());
Pregunta: yo estoy usando un dto y su método en el mapper, los cuales ya estaban creados. Digamos, alguien más los está usando. Si yo agrego un atributo a ese dto y en su método del mapper le agrego el set de ese método: le puedo llegar a romper todo al que había creado ese dto/mapper? La "buena práctica" aquí es crear mi dto/método mapper? O reutilizar código?

2022-02-10 12:40 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/NewsService.java
> +    return newsMapper.map(result.get());
@nardo1285 No me queda muy en claro el escenario, pero para no romper nada lo que podes hacer es agregar el enum de attributes al mapper como se ha hecho en otros mappers y si este método se esta utilizando en otro lado, le pasas los attributes que necesite para ese mapeo y acá agregas los que vos necesites. No sé si eso responde a tu pregunta...?

2022-02-11 22:23 UTC, nardo1285 commented
Estos conflictos son porque modifiqué los métodos (ya usados por otros) en los mappers?

2022-02-12 23:05 UTC, nardo1285 commented
Magui, ahí resolví los conflictos. Se me complicó con el tema de las versiones en local, @FrancoGL me dió una mano! 
Slds.

2022-02-13 14:49 UTC, mkain0 requested changes

2022-02-13 14:49 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/response/NewsResponse.java
> +  private Category idCategory;
Category es una entity. Nunca deben ser expuestas por el servicio

2022-02-13 14:49 UTC, mkain0 commented on src/main/java/com/alkemy/ong/mapper/attribute/NewsAttributes.java
> +  CATEGORY_ID("category_id");
CamelCase para el String entre paréntesis

2022-02-13 23:13 UTC, nardo1285 commented on src/main/java/com/alkemy/ong/model/response/NewsResponse.java
> +  private Category idCategory;
Solved!

2022-02-13 23:13 UTC, nardo1285 commented on src/main/java/com/alkemy/ong/mapper/attribute/NewsAttributes.java
> +  CATEGORY_ID("category_id");
Solved!

2022-02-14 00:00 UTC, mkain0 approved these changes

2022-02-14 00:03 UTC, merged