OT132-53: Create Contact's model and repository
alkemyTech/OT132-SERVER pull request #8
Opened 2022-01-20 21:55 UTC by FrancoGL

Added entity Contact with its repository.

2022-01-20 23:09 UTC, mkain0 requested changes

2022-01-20 23:09 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/entity/Contact.java
> +@Table(name = "CONTACTS")
Falta el @Entity

2022-01-20 23:09 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/entity/Contact.java
> +  private Timestamp deleteAt;
TYPO: deletedAt

2022-01-20 23:09 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/entity/Contact.java
> +  @CreationTimestamp
Esta annotation no corresponde a este campo, ya que el mismo se utiliza como soft delete, no como campo de auditoria.

2022-01-20 23:09 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/entity/Contact.java
> +  @Column(name = "DELETE_AT")
TYPO: DELETED_AT

2022-01-21 01:13 UTC, FrancoGL commented on src/main/java/com/alkemy/ong/model/entity/Contact.java
> +@Table(name = "CONTACTS")
Maga, el @Entity lo coloqué, o te refieres a otro elemento?

2022-01-21 09:28 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/entity/Contact.java
> +@Table(name = "CONTACTS")
Ufff... no lo ví. Mala mia!  :)

2022-01-21 15:56 UTC, mkain0 approved these changes

2022-01-21 15:57 UTC, merged