Ot132-98 Test: Endpoints /testimonials
alkemyTech/OT132-SERVER pull request #89
Opened 2022-02-19 00:52 UTC by KharonBlue

2022-02-19 14:23 UTC, mkain0 requested changes

2022-02-19 14:23 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +  @ApiOperation(value = "Create a testimonial", produces = "application/json")
Está operación consume and produce son JSON porque son el tipo de entrada y salida de la API.

2022-02-19 14:23 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/TestimonialController.java
> +  @PutMapping(value = "{id}", produces = {"application/json"})
Aquí lo mismo. Consume and produce son JSON

2022-02-19 14:23 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/testimonial/AbstractBaseTestimonialIntegrationTest.java
> +    when(testimonialRepository.findBySoftDeleteFalseOrderByTimestampDesc(any()))
Any de que type?

2022-02-19 14:23 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/testimonial/CreateTestimonialIntegrationTest.java
> +    assertEquals(HttpStatus.BAD_REQUEST, response.getStatusCode());
Duplicate code. Por favor, reutilizar los métodos como estaba anteriormente.

2022-02-19 14:23 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/testimonial/DeleteTestimonialIntegrationTest.java
> +    when(testimonialRepository.findByTestimonialIdAndSoftDeleteFalse(TESTIMONIAL_ID)).thenReturn(
Missing eq matcher.

2022-02-19 14:23 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/testimonial/DeleteTestimonialIntegrationTest.java
> +        createTestimonialStub());
Missing eq matcher.

2022-02-19 14:23 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/testimonial/DeleteTestimonialIntegrationTest.java
> +    when(testimonialRepository.findByTestimonialIdAndSoftDeleteFalse(TESTIMONIAL_ID)).thenReturn(
Missing eq matcher.

2022-02-19 14:23 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/testimonial/DeleteTestimonialIntegrationTest.java
> +    setAuthorizationHeaderBasedOn(RoleType.ADMIN);
No conduce con el type mencionado en el título del test.

2022-02-19 14:23 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/testimonial/DeleteTestimonialIntegrationTest.java
> +    assertEquals(HttpStatus.NOT_FOUND, response.getStatusCode());
Código duplicado: por favor, reutilizar los métodos de las clases padre.

2022-02-19 14:23 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/testimonial/UpdateTestimonialIntegrationTest.java
> +  private void assertEmptyOrNullFieldInRequest(ResponseEntity<ErrorResponse> response,
Duplicate code: Este método ya existe en la clase padre. Está clase no debería tener cambios en el scope de este PR.

2022-02-19 17:11 UTC, KharonBlue commented on src/test/java/com/alkemy/ong/integration/testimonial/DeleteTestimonialIntegrationTest.java
> +    assertEquals(HttpStatus.NOT_FOUND, response.getStatusCode());
El de la clase padre devuelve un 400 y aca se requiere un 404

2022-02-19 17:11 UTC, KharonBlue commented on src/test/java/com/alkemy/ong/integration/testimonial/DeleteTestimonialIntegrationTest.java
> +    assertEquals(HttpStatus.NOT_FOUND, response.getStatusCode());
Deberia añadir un metodo en la clase padre que devuelva el 404?

2022-02-21 09:38 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/testimonial/DeleteTestimonialIntegrationTest.java
> +    assertEquals(HttpStatus.NOT_FOUND, response.getStatusCode());
Agrega un nuevo parametro para pasar el status code. Siempre hay que reutilizar el código.

2022-02-21 09:50 UTC, mkain0 approved these changes

2022-02-21 09:52 UTC, mkain0 approved these changes

2022-02-21 09:58 UTC, mkain0 approved these changes

2022-02-21 09:59 UTC, mkain0 approved these changes

2022-02-21 10:01 UTC, merged