Ot132 26
alkemyTech/OT132-SERVER pull request #9
Opened 2022-01-21 14:41 UTC by VladimirMorote

2022-01-21 16:25 UTC, mkain0 requested changes
@VladimirMorote este ticket excede el scope del ticket. Por favor, revisar los comentarios del ticket para cumplir con el scope del ticket. Si tienes dudas, consulta con tus compañeros, durante la planning fuimos por marcando que partes del video https://www.youtube.com/watch?v=X80nJ5T7YpE&ab_channel=JavaBrains corresponden a cada ticket de Spring Security.

2022-01-22 17:23 UTC, VladimirMorote commented
correcion

2022-01-22 18:13 UTC, mkain0 requested changes
@VladimirMorote por favor, revisa los merge conflicts. Una vez que los resuelvas solicita "Re-review request". Gracias!

2022-01-22 19:18 UTC, mkain0 commented on pom.xml
> +    </dependency>
Esta dependencia ya existe en el pom.xml desde la base del proyecto.

2022-01-22 19:27 UTC, mkain0 approved these changes

2022-01-22 19:28 UTC, merged

2022-01-22 19:30 UTC, mkain0 commented
@VladimirMorote mergeo este PR con los fixes necesarios porque esto esta bloqueando el push a todo el equipo.

2022-01-28 17:48 UTC, VladimirMorote commented
Cómo estás. Me vas a disculpar pero no puedo asistir hoy. Tengo ya
encaminado mí primer ticket, le falta muy poquito. Me quiero concentrar en
estudiar más este fin de semana. Las compañeras Inti y Agos unas genias, me
dieron una mano.

Saludos y buen fin de semana.

El vie., 21 ene. 2022 13:25, mkain0 ***@***.***> escribió:

> ***@***.**** requested changes on this pull request.
>
> @VladimirMorote <https://github.com/VladimirMorote> este ticket excede el
> scope del ticket. Por favor, revisar los comentarios del ticket para
> cumplir con el scope del ticket. Si tienes dudas, consulta con tus
> compañeros, durante la planning fuimos por marcando que partes del video
> https://www.youtube.com/watch?v=X80nJ5T7YpE&ab_channel=JavaBrains
> corresponden a cada ticket de Spring Security.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/alkemyTech/OT132-SERVER/pull/9#pullrequestreview-859769807>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALFKX5MPIRAN35K4LZIX5FDUXGCIFANCNFSM5MPWILGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>