OT132-94
alkemyTech/OT132-SERVER pull request #90
Opened 2022-02-21 15:15 UTC by nardo1285

2022-02-21 16:27 UTC, mkain0 requested changes

2022-02-21 16:27 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/activities/CreateActivityIntegrationTest.java
> +    assertEquals("Content cannot be empty or null.", getFirstMessageError(response));
REUTILIZAR EL CODIGO EXISTENTE: assertOneEmptyOrNullFieldInRequest

2022-02-21 16:27 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/activities/CreateActivityIntegrationTest.java
> +    assertEquals("Name cannot be empty or null.", getFirstMessageError(response));
REUTILIZAR EL CODIGO EXISTENTE: assertOneEmptyOrNullFieldInRequest

2022-02-21 16:27 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/activities/CreateActivityIntegrationTest.java
> +    assertEquals("Name cannot be empty or null.", getFirstMessageError(response));
REUTILIZAR EL CODIGO EXISTENTE: assertOneEmptyOrNullFieldInRequest

2022-02-21 16:27 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/activities/CreateActivityIntegrationTest.java
> +    assertEquals("Content cannot be empty or null.", getFirstMessageError(response));
REUTILIZAR EL CODIGO EXISTENTE: assertOneEmptyOrNullFieldInRequest

2022-02-21 16:27 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/activities/CreateActivityIntegrationTest.java
> +    assertEquals("Image cannot be empty or null.", getFirstMessageError(response));
REUTILIZAR EL CODIGO EXISTENTE: assertOneEmptyOrNullFieldInRequest

2022-02-21 16:27 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/activities/CreateActivityIntegrationTest.java
> +    assertEquals("Image cannot be empty or null.", getFirstMessageError(response));
REUTILIZAR EL CODIGO EXISTENTE: assertOneEmptyOrNullFieldInRequest

2022-02-21 16:27 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/activities/UpdateActivityIntegrationTest.java
> +    assertEquals(400, getStatusValue(response));
REUTILIZAR EL CODIGO EXISTENTE: assertOneEmptyOrNullFieldInRequest

2022-02-21 16:27 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/activities/UpdateActivityIntegrationTest.java
> +    assertEquals(400, getStatusValue(response));
REUTILIZAR EL CODIGO EXISTENTE: assertOneEmptyOrNullFieldInRequest

2022-02-21 16:27 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/activities/UpdateActivityIntegrationTest.java
> +    assertEquals("Content cannot be empty or null.", getFirstMessageError(response));
REUTILIZAR EL CODIGO EXISTENTE: assertOneEmptyOrNullFieldInRequest

2022-02-21 16:27 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/activities/UpdateActivityIntegrationTest.java
> +    assertEquals("Content cannot be empty or null.", getFirstMessageError(response));
REUTILIZAR EL CODIGO EXISTENTE: assertOneEmptyOrNullFieldInRequest

2022-02-21 16:27 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/activities/UpdateActivityIntegrationTest.java
> +    assertEquals("Image cannot be empty or null.", getFirstMessageError(response));
REUTILIZAR EL CODIGO EXISTENTE: assertOneEmptyOrNullFieldInRequest

2022-02-21 16:27 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/activities/UpdateActivityIntegrationTest.java
> +    assertEquals("Image cannot be empty or null.", getFirstMessageError(response));
REUTILIZAR EL CODIGO EXISTENTE: assertOneEmptyOrNullFieldInRequest

2022-02-21 16:27 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/activities/UpdateActivityIntegrationTest.java
> +    assertEquals(404, getStatusValue(response));
REUTILIZAR EL CODIGO EXISTENTE: assertObjectNotFound

2022-02-21 16:27 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/activities/UpdateActivityIntegrationTest.java
> +    assertEquals(404, getStatusValue(response));
REUTILIZAR EL CODIGO EXISTENTE: assertObjectNotFound

2022-02-21 16:27 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/activities/UpdateActivityIntegrationTest.java
> +    assertEquals(HttpStatus.OK, response.getStatusCode());
Faltan los assert para comprobar que los atributos de la response son los esperados.

2022-02-21 16:27 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/activities/UpdateActivityIntegrationTest.java
> +    assertEquals(HttpStatus.OK, response.getStatusCode());
Faltan los assert para comprobar que los atributos de la response son los esperados.

2022-02-22 02:38 UTC, nardo1285 commented
Bueno, le metí manija al tema de reutilizar código...quizá me pasé de mambo, pero estuvo divertío. 
:)

2022-02-22 09:19 UTC, mkain0 approved these changes

2022-02-22 09:20 UTC, merged